### ISSUE TITLE
Resetting immobile vehicles

### ISSUE THREAD

**Issue by vmikulik** [Group6OxCS/game#17]
Currently, if a car gets stuck and is not able to move, the game enters a softlock state which cannot be left except by reloading.  

I suggest we fix this by detecting a car that's immobile for more than x seconds, and teleport it to the last track marker it visited.

**Comment by matsjoyce** [comment]
Ooo, I was thinking about this recently as well. It might be better to just kill the player, same as if the car is too damaged (#11).

**Comment by vmikulik** [comment]
That could work too, depending on how hardcore we want this simulation to be. I kind of like the idea of incentivising reckless driving by being a bit more forgiving – it should make for more interesting races. I think if we punish the player too much for collisions, people will just go very slowly. Additionally, it's important to remember that being immobile for a while is a punishment in itself, and will cost precious lap time.

**Comment by matsjoyce** [comment]
Maybe. I suppose this is something we should discuss with the customer. But once implemented it should be easy to switch from hardcore to forgiving or vice versa, so we don't need to decide yet.
