### ISSUE TITLE
Track collectables

### ISSUE THREAD

**Issue by matsjoyce** [Group6OxCS/game#18]
Do we want pickupable things on the track, such as extra nitro? Or it this too silly and complicated?

**Comment by vmikulik** [comment]
I think adding Nitro collectibles would be a good idea, and would incentivise more interesting AIs.

**Comment by matsjoyce** [comment]
One question. How should collectables interact with obstacle detection? Should they show up, in which case how do we differentiate them from trees, or should they not show up (they aren't obstacles after all) in which case how can the AI find them? We could add an extra data point for bearing and distance to nearest collectable.

**Comment by vmikulik** [comment]
I’d say we give info about collectables via a separate channel, as you suggest.
