### ISSUE TITLE
Improved track loader

### ISSUE THREAD

**Issue by matsjoyce** [Group6OxCS/game#19]
The track loader looks... ugly. Do the following to make it look nicer:

 - [x] Make better track images
 - [x] Create better descriptions / names of tracks
 - Anything else?

**Comment by vmikulik** [comment]
I'd say this would also involve prettifying the level1 track a bit – adding grass and trees and so on.

May I suggest renaming it something like 'Canyon run'? It is pretty canyon-like, I think. But maybe Mani should have the honour of naming it, given it's his design?

**Comment by matsjoyce** [comment]
@yordun Can you name + write a description for your track? I'm going to have a go at the better images part.

**Comment by matsjoyce** [comment]
Images have been done for SimpleTrack and DesertInfinity. Waiting for #22 before I do level1.

**Comment by matsjoyce** [comment]
All remaining work on this has been taken over by #22.
