### ISSUE TITLE
Upgrade Track Markers (?)

### ISSUE THREAD

**Issue by vmikulik** [Group6OxCS/game#21]
Some tracks have branching paths. Should we admit this type of behaviour, and if so, how?

One way this could be implemented is by making them hard-coded 'shortcut' objects, and to make sure that there is a track marker on either end of the shortcut. This way, the car can choose to follow a shortcut once it becomes available instead of the next real node – and once the shortcut is completely taken, the normal track marker logic is sufficient to return the car on track.

(Also, I think we should increase the amount of track markers, so the car can potentially make more use of the track's shape. This is a matter of opinion, of course)

**Comment by matsjoyce** [comment]
On Mani's track I have put markers at each end of the shortcut, and none on the longer route. I haven't experimented with using AIs on Mani's track yet, so I'll have to see how it goes, but what I have observed is that one of my AIs could almost complete your track without using waypoints at all. It only got confused in one area where the tarmac was indistinguishable from some grass, so I think extra waypoints may not add that much for the effort needed. I'll experiment and post more findings soon.
