### ISSUE TITLE
Sound bug in web version

### ISSUE THREAD

**Issue by vmikulik** [Group6OxCS/game#30]
When you run the game on the website, the engine noise (I think; I don’t know certainly what exactly does it) makes an ugly recurring sound. It really detracts from the game’s soundscape, and should be fixed for the final version.

**Comment by matsjoyce** [comment]
I have looked into this and for the ticking noise there doesn't seem to be much we can do. The problem is latency between the clip stopping and starting again. I have fiddled with all of the available settings, and nothing changes, so I think we will just have to put up with it. :disappointed:
