### ISSUE TITLE
Inconsistent speed measurements 

### ISSUE THREAD

**Issue by vmikulik** [Group6OxCS/game#35]
At the moment, it seems that we get inconsistent speed readings from manual speed measurements (rb.velocity.magnitude) and from CarController.CurrentSpeed. 

Which one is canonical? Why does this happen? Does it matter?

**Comment by matsjoyce** [comment]
`rb.velocity.magnitude` is in m/s which we want, `CarController.CurrentSpeed` is in MPH.
